name: Master CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Check the Dockerfiles
      run: ./check_docker.sh
    - name: Build the Docker images
      run: ./build_docker.sh
    - name: Push the images to Docker Hub
      run: ./push_docker.sh
    - name: Clean up
      run: ./clean_docker.sh
